### ISSUE TITLE
Error during calibration

### ISSUE THREAD

**Issue by UBela** [marcus-nystrom/Titta#15]
Hi,
sometime when starting to calibrate i get the following error message and i am not sure what to make of it:

`Traceback (most recent call last):
  File "PATH_TO_SCRIPT", line 79, in <module> 
  File "PATH_TO_SCRIPT\titta\Tobii.py", line 425, in calibrate
    self.animator = helpers.AnimatedCalibrationDisplay(self.win, target, 'animate_point')
  File "PATH_TO_SCRIPT\titta\helpers_tobii.py", line 539, in __init__
    self.screen_refresh_rate = float(win.getActualFrameRate())
TypeError: float() argument must be a string or a number, not 'NoneType'`

Line 79 in my code is where the calibrate() function is called. The error does not appear all the time which makes it more confusing to me. Thanks in advance!

**Comment by marcus-nystrom** [comment]
Hi,

Looks like the problem is that win.getActualFrameRate() can return None,
see documentation:
https://www.psychopy.org/api/visual/window.html

I temporary fix would be to hardcode this parameter in your setup (check
the screen refresh rate for your particular setup), so instead of (in
helpers_tobii.py, line 539)
self.screen_refresh_rate = float(win.getActualFrameRate())

type

self.screen_refresh_rate = 60.0 # If you screen refresh rate is 60 Hz.

I will implement  a more permanent fix.

Thanks for reporting!
