### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by ChrisCo74** [marcus-nystrom/Titta#22]
Hi,
Program tested: extract_trial_data_and_detect_fixation.py from the 'resources' folder.
I tried run the 'testfile.pkl' from same folder and get an error : 
line 31, in extract_trial_data
    start_idx = np.where(df_msg.msg == msg_onset) [0] [0]
IndexError: index 0 is out of bounds for axis 0 with size 0

I also tried with another .pkl file created after running the antisaccade task demo and have the same error.
Thanks for help.
Regards,
Christophe.

**Comment by marcus-nystrom** [comment]
Dear Christophe,

Thanks for your question!

To test with a result (.pkl) file you recorded yourself, you need to modify
the messages on lines 86 and 87. Otherwise you will get the error you
describe below (indicates that the message you input to the function
'extract_trial_data' cannot be found among the sent messages).

I have updated the help text in the .py-file to clarify this.

Thanks,
Marcus
