### ISSUE TITLE
Callback function for gaze data

### ISSUE THREAD

**Issue by rhardstone** [marcus-nystrom/Titta#54]
Is it possible with titta to associate a callback function when recording similar to that from the tobii_research SDK?

e.g. with tobii_research:
tracker.subscribe_to(tr.EYETRACKER_GAZE_DATA, callback=gaze_data_callback, as_dictionary=True)

**Comment by dcnieho** [comment]
You mean to use your own callback function instead of simply having samples arrive to our buffers?
1. No
2. You wouldn't want to do this, as its very hard to write correct python code that ensures that no data is lost using these callbacks. That, for instance, can happen is you do not sleep or yield often enough due to which the callback cannot run.

**Comment by marcus-nystrom** [comment]
> You mean to use your own callback function instead of simply having samples arrive to our buffers?
> 
> 1. No
> 2. You wouldn't want to do this, as its very hard to write correct python code that ensures that no data is lost using these callbacks. That, for instance, can happen is you do not sleep or yield often enough due to which the callback cannot run.

Just to clarify:  occasional data loss when using callbacks in the tobii_research SDK (previously used in Titta)  is the reason we abandoned the Tobii Python SDK altogether in favor of TittaPy.

**Comment by rhardstone** [comment]
Thanks for the quick response,  that is very helpful and answers my question
